"""remove priority

Revision ID: 47a4f13bf494
Revises: ffeec5acd68d
Create Date: 2026-02-11 12:30:58.321833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a4f13bf494'
down_revision: Union[str, Sequence[str], None] = 'ffeec5acd68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
